u-boot-fw-utils: drop bbappend file
commit 725dc5e0e2b137ebabcd67d1018572901e2366ed ("Drop u-boot-fw-utils"), removes
all the config files related to the u-boot-fw-utils recipe but not the bappend
file itself.

Fixes:

ERROR: No recipes available for:
  /home/bdx-iot/koncepto/nxp/meta-swupdate-boards/recipes-bsp/u-boot/u-boot-fw-utils_%.bbappend

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>